alias ls='ls --color=auto'
alias ll='ls'
alias rm='rm --one-file-system'
alias grep='grep --color=auto'
alias rgrep='grep --color -rn'
alias diff='colordiff'
alias vim='nvim'
alias vi='vim'
alias v='vim'
alias m='make -j8'
alias g='git'
alias s='sync'
alias ckermit='ckermit -c'
alias kermit0='ckermit -c -y /home/$(whoami)/.kermrc -l /dev/ttyS0'
alias kermit1='ckermit -c -y /home/$(whoami)/.kermrc -l /dev/ttyUSB0'
alias kermit2='ckermit -c -y /home/$(whoami)/.kermrc -l /dev/ttyUSB1'
alias kermit3='ckermit -c -y /home/$(whoami)/.kermrc -l /dev/ttyUSB2'
alias i3lock='i3lock --color=000000'
alias sudo='sudo '
